---
title: "PROJECT 01: Spatial distribution of Fire incidents in D.C & Maryland & Virginia in 2018"
author: "Jeongwon Yoo
         Simbanegavi Simbarashe
      	Nithin Ravindra Reddy 
"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: show
    number_sections: false
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'

```{r setup, include=FALSE}

# Set CRAN mirror
options(repos = c(CRAN = "https://cloud.r-project.org"))
# Install required packages if they are not already installed
required_packages <- c("sf", "ggplot2")
new_packages <- required_packages[!(required_packages %in% installed.packages()[, "Package"])]
if (length(new_packages)) {
  install.packages(new_packages)
  install.packages(c("sf", "tidyverse"))

}
# Load libraries
library(sf)
library(ggplot2)
```


```{r setup, include=FALSE}
# Some of common RMD options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
knitr::opts_chunk$set(results="markup", warning = F, message = F)
# Can globally set option for number display format.
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
```

