---
title: "Forecasting Wildfire Events from Climate Indicators: A Comparative ML Study"
author:
  Jeongwon Yoo  
  Simbanegavi Simbarashe  
  Nithin Ravindra Reddy  
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: show
    number_sections: false
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r setup, include=FALSE}
# Set CRAN mirror
options(repos = c(CRAN = "https://cloud.r-project.org"))

library(corrplot)
library(dplyr)
library(ezids)
library(e1071)
library(ggplot2)
library(ROCR)
library(gridExtra)
library(lubridate)
library(randomForest)
library(readr)
library(rpart)
library(rpart.plot)
library(viridis)
library(spdep)
library(spatialreg)
library(smotefamily)
library(sf)
library(tigris)
library(tidyr)
library(tidymodels)
library(treemapify)

knitr::opts_chunk$set(echo = TRUE, results = "markup", warning = FALSE, message = FALSE)
options(scientific = TRUE, digits = 3)
```

# CHAPTER 1: Introduction

## 0. Overview

## 1. Objectives

## 2. Research Questions

## 3. Significance of the Study

## 4. Weakness of the Study

### 1.4.1 Imbalanced Data

# CHAPTER 2 : EDA


# CHAPTER 3 : Methodology

## 1. Preprocessing pipeline (SMOTE)

## 2. Train & Test split

## 3. Modeling strategy

### 3.3.1 KNN

### 3.3.2 SVM

### 3.3.3 Random Forest

### 3.3.4 Decision Tree

### 3.3.5 Logistic Regression

# CHAPTER 4 : Conclusion & Future Works

## 1. Summary of Findings

Our analysis examined the relationship between climate variables and wildfire occurrence.
The primary challenge was the extreme class imbalance, which caused most baseline models to fail at detecting wildfire events.
SMOTE-based preprocessing improved the model's ability to learn the minority class, allowing us to evaluate which algorithms performed best in predicting wildfire events.

## 2. Best Performing Model and Justification

## 3.Limitations of the Study

Despite improvements with SMOTE, the models still struggled to achieve high precision, indicating difficulty in correctly distinguishing non-wildfire events from actual fires.

In addition, the dataset contains limited feature diversity, relying primarily on climate variables, without incorporating vegetation dryness, human activity, or land cover features.

Finally, the temporal split (2018 train / 2019 test) reflects real-world conditions but introduces year-to-year variability that may reduce generalizability.

## 4. Future Works